import * as XLSX from 'xlsx';
import type { ReportColumn, ReportColumnType, ReportResult, ReportTable } from '../api/endpoints';
import { downloadWorkbook, slug } from './spreadsheet';

const NUMERIC: ReportColumnType[] = ['int', 'number', 'decimal', 'percent', 'money'];

export const isNumeric = (t: ReportColumnType) => NUMERIC.includes(t);

/** How a report value is shown on screen (the PDF uses the same rules). */
export function formatCell(v: unknown, type: ReportColumnType): string {
  if (v == null || v === '') return '';
  if (isNumeric(type)) {
    const n = Number(v);
    if (!Number.isFinite(n)) return String(v);
    if (type === 'int') return Math.round(n).toLocaleString();
    if (type === 'percent') return `${n.toFixed(1)}%`;
    if (type === 'number') return n.toLocaleString(undefined, { maximumFractionDigits: 2 });
    return n.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  }
  return String(v);
}

/** Headline figures are already worded on the server; just add thousands separators to plain numbers. */
export function formatStat(v: unknown): string {
  if (v == null || v === '') return '—';
  if (typeof v === 'number') return Number.isInteger(v) ? v.toLocaleString() : String(v);
  return String(v);
}

/** Spreadsheet header: percentages say so, since the cell holds the plain number. */
const header = (c: ReportColumn) => (c.type === 'percent' ? `${c.label} (%)` : c.label);

/** Numbers stay numbers so Excel can add them up. */
const sheetValue = (v: unknown, c: ReportColumn) => {
  if (v == null) return '';
  if (isNumeric(c.type)) { const n = Number(v); return Number.isFinite(n) ? n : String(v); }
  return String(v);
};

export const tableAoa = (t: ReportTable): unknown[][] =>
  [t.columns.map(header), ...t.rows.map(r => t.columns.map(c => sheetValue(r[c.key], c)))];

const stamp = () => new Date().toISOString().slice(0, 10);

export const reportFileName = (r: ReportResult, suffix?: string) =>
  `${slug(r.title)}${suffix ? '-' + slug(suffix) : ''}-${stamp()}`;

/** Every table as its own sheet, after a sheet with what the report covers and its headline figures. */
export function downloadReportExcel(r: ReportResult) {
  const about: unknown[][] = [
    ['Report', r.title],
    ['About', r.description],
    ...r.scope.map(s => { const i = s.indexOf(':'); return i > 0 ? [s.slice(0, i), s.slice(i + 1).trim()] : ['', s]; }),
    ['Generated', new Date(r.generatedAt).toLocaleString()],
    ...(r.generatedBy ? [['Generated by', r.generatedBy]] : []),
    [],
    ['Figure', 'Value', 'Detail'],
    ...r.summary.map(s => [s.label, typeof s.value === 'number' ? s.value : formatStat(s.value), s.hint ?? '']),
    ...(r.notes.length ? [[], ['Notes'], ...r.notes.map(n => [n])] : []),
  ];
  const used = new Set<string>(['Summary']);
  const sheets = r.tables.map(t => {
    let name = t.title.replace(/[[\]:*?/\\]/g, ' ').slice(0, 31).trim() || 'Table';
    for (let i = 2; used.has(name.toLowerCase()); i++) name = `${name.slice(0, 27)} (${i})`;
    used.add(name.toLowerCase());
    return { name, rows: tableAoa(t) };
  });
  downloadWorkbook(reportFileName(r), [{ name: 'Summary', rows: about }, ...sheets]);
}

/** One table as a CSV file (UTF-8 with a byte-order mark, so Excel shows names with accents correctly). */
export function downloadTableCsv(r: ReportResult, t: ReportTable) {
  const csv = XLSX.utils.sheet_to_csv(XLSX.utils.aoa_to_sheet(tableAoa(t)));
  const url = URL.createObjectURL(new Blob(['﻿' + csv], { type: 'text/csv;charset=utf-8' }));
  const a = document.createElement('a');
  a.href = url;
  a.download = `${reportFileName(r, r.tables.length > 1 ? t.title : undefined)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
